### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#1]

**Comment by joshman58** [comment]
Design the landing page

**Comment by OyesolaTobi** [comment]
Duly noted with thanks.

**Comment by OyesolaTobi** [comment]
I created the landing page (this is the page any new user would  see first once they click on our link) afterwards the user would either login or sign up. The home page can only be accessed by those who have an account with us. 

[Landing and home page.pdf](https://github.com/zuri-training/Project-QR-Gen-Team-52-Frontend/files/9233917/Landing.and.home.page.pdf)

[https://www.figma.com/file/jPe6HV2Vkay0U5weAh0CYn/Landing-and-Home-page?node-id=2%3A1770](url)

**Comment by joshman58** [comment]
Great job Oluwatobiloba. Please move the task to the "Done" column. 
Thanks

**Comment by OyesolaTobi** [comment]
I'm unable to drag it, I think there's an issue
