### ISSUE TITLE
Sign up page Redo

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#14]

**Comment by Favtob** [comment]
[signup html](https://github.com/zuri-training/Project-QR-Gen-Team-52-Frontend/blob/develop/Pages/signup.html)
[signup css](https://github.com/zuri-training/Project-QR-Gen-Team-52-Frontend/blob/develop/Pages/signup.css)

**Comment by joshman58** [comment]
Please move this issue to Task review, except if it has been reviewed and certified done by the Dev team lead.

**Comment by Favtob** [comment]
Okay.

**Comment by joshman58** [comment]
Good job
