### ISSUE TITLE
Foundational Research

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#24]

**Comment by OyesolaTobi** [comment]
Foundational Research was carried out to answer the questions;
1. What should we build? 
2. What are the users problems?
3. How can we solve them?

The goal of our foundational research was to help define the problem we would like to design for.

We carried out the first half of the foundational research by adopting the method of the secondary research (information someone has put together) by reading reviews dropped about users of other Qr code generators. 
The pain points gathered from the secondary research are;
1. Application crashing at start points
2. Too many advertisement
3. QR code generated not scanning
4. Inability to scan generated QR codes with other applications
5. No free trial
6. Qr code generated not getting saved to phone
7. No cloud storage
8. All details not being captured in the generated code
9. Application only available on Android Operating system
10. Invalid Qr after generation
11. UFT8 code not generated, only ASCII

The information gathered from our secondary research is giving us a lead on how to carry out our primary research (research conducted by ourselves)
