### ISSUE TITLE
Research plan

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#26]

**Comment by holuwamueewer** [comment]
A research plan was drafted to help us develop screener questions and research questions and gain insight into the motivations and pain points of QR code users.

**Comment by holuwamueewer** [comment]
https://docs.google.com/document/d/1z6AUO5sRB1jj5OaFcWtwIY6w-Wz-vbCVgtTdQMfQOE0/edit?usp=sharing

**Comment by solo-blaze** [comment]
the research plan aided our understanding about the project , giving us more insight about the users pain point and goal in carrying out their task.
