### ISSUE TITLE
Empathy Map

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#29]

**Comment by Doyeen91** [comment]
https://www.figma.com/file/7ntQSfo6moEKgs6kwiR90X/Empathy-map%2FUser-story%2FUser-flow-for-QR-code-generator?node-id=0%3A1
The empathy map was designed from the responses of the respondents interviewed. Pain points were drawn out of these responses, user personas were designed which helped in coming up with articulated ideas.

**Comment by ben11997** [comment]
the emphaty map task is completed, pls find below link for assigned task.
