### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#3]
Create Dashboard for a QR generation web app.

**Comment by thintallqomar** [comment]
We've completed the wireframe, lofi and hifi designs of the dashboard task given to you. We are waiting for it to be reviewed.

**Comment by holuwamueewer** [comment]
https://www.figma.com/file/aDrP9Zxdz9kmdahWYtfWXu/Dashboard-wireframe%2C-lofi%2C-hifi?node-id=0%3A1

**Comment by joshman58** [comment]
Good job

**Comment by joshman58** [comment]
Good job.
