### ISSUE TITLE
User flow

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#30]

**Comment by solo-blaze** [comment]
https://www.figma.com/file/7ntQSfo6moEKgs6kwiR90X/Empathy-map-User-story-User-flow-for-QR-code-generator 

the user flow was made to map out how the user can easily navigate through the whole website. this user flow was use as a guide to know the number of screens which it will take for users to carry out their task perfectly and was also a guide in designing this pages in order not to place unnecessary features to the design
