### ISSUE TITLE
User persona

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#31]

**Comment by OyesolaTobi** [comment]
[https://docs.google.com/presentation/d/12qS-xu272XSyJLkq-nAcB7fsCtjT5o61Usi9uW_IBS8/edit?usp=sharing](url)

I worked on the user persona.
The 1st user persona describes a set of people who have a lot to do and still wish to make use of the Qr code generator without stress and with the ability to change colours (edit)
The 2nd user persona represents a set of people who wish to share the Qr code generated with so much of ease
