### ISSUE TITLE
Style guide (Typography)

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#37]

**Comment by OyesolaTobi** [comment]
[https://www.figma.com/file/RJCOiSkn2nBWGm65DWzKEC/Typography-for-team-52?node-id=0%3A1](url)

Decided to make use of Montserrat because of the nature of application we are working with
Montserrat has so many styles to it which it easier to maintain a single font type but different styles
