### ISSUE TITLE
Style guide (Notification)

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#42]

**Comment by joshman58** [comment]
Please include a link to your work

**Comment by tawakkul007** [comment]
In order to ease responsiveness and interaction with the user, we created pop-up notifications

https://www.figma.com/file/02M8fdUF8EyK1sVzeyKML3/Notifications-for-style-guide?node-id=0%3A1

**Comment by joshman58** [comment]
Good job.
