### ISSUE TITLE
Style guide (Input fields)

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#43]

**Comment by joshman58** [comment]
Please include a link to your work

**Comment by ebehdeborah** [comment]
Okay. I'll do that.

**Comment by ebehdeborah** [comment]
[https://www.figma.com/file/qhq60aeY9TF1k9gfdakJF6/Input-field-for-Team-52?node-id=0%3A1](url)
