### ISSUE TITLE
Logo creation & Logo types

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#44]

**Comment by OyesolaTobi** [comment]
[https://www.figma.com/file/VZu6EEahhX9NPknsowAC6o/Logo-types-and-creation-for-Team-52?node-id=0%3A1](url)

Worked on the logo.
The logo idea was to keep it simple and unique to the team. 
Decided to make use of the team number for easy identification
