### ISSUE TITLE
Create Error 404 screen

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#47]

**Comment by thintallqomar** [comment]
Done and under Review

![Image](https://user-images.githubusercontent.com/105394481/183282168-fccf6b95-a0eb-4549-900a-eedb6e9e3d79.png)

**Comment by thintallqomar** [comment]
https://www.figma.com/file/xCNIX4RJKkAGn2OnsC4UQt/404?node-id=0%3A1

**Comment by joshman58** [comment]
Weldon.
