### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#48]

**Comment by lizzy-osuwa03** [comment]
I created the about us page to show the reflection of the purpose and personality of the QR Team 52 code generating system to its owners or employees.

Please find below the link to the About Us page.
https://www.figma.com/file/1g4hAgOiGRBuPEJGPnRWKj/Zuri-Team-52-(Qr-generator)?node-id=1384%3A7221
