### ISSUE TITLE
Qr Code Colour selection page & Contact us page

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#5]

**Comment by ben11997** [comment]
In progress

**Comment by joshman58** [comment]
Please add a link to your work and close it if done.
Thanks

**Comment by thephotosamurai** [comment]
https://www.figma.com/file/1g4hAgOiGRBuPEJGPnRWKj/Zuri-Team-52-(Qr-generator)?node-id=107%3A753
