### ISSUE TITLE
Qr Code generated page, Qr code failure & Qr Code Successful

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#6]

**Comment by joshman58** [comment]
Please add the link to your work on the issue

**Comment by Doyeen91** [comment]
https://www.figma.com/file/1g4hAgOiGRBuPEJGPnRWKj/Zuri-Team-52-(Qr-generator)?node-id=1%3A4
 
Inspirations were gotten from Behance, Dribble and Pinterest sites to see similar websites with good designs, the color scheme used were predetermined by the team as well as the typography, grids and all other inputs were all gotten from the style guides created.

**Comment by Miade-x** [comment]
https://www.figma.com/file/DlQ2mDQELHyxJBnElDo2RK/QR-code-generator-screens


Done already.
